
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 13 13:34:35 GMT+07:00 2012
//----------------------------------------------------

package ru.tsu.inf.cdel.parser;

/** CUP generated class containing symbol constants. */
public class LexemeType {
  /* terminals */
  public static final int LEFTBRACKET = 35;
  public static final int DIVIDE = 32;
  public static final int STRING_LITERAL = 39;
  public static final int FUNCTION = 4;
  public static final int EQUALS = 19;
  public static final int RIGHTBRACKET = 36;
  public static final int NOTEQUAL = 24;
  public static final int ARRAY = 5;
  public static final int LESS = 25;
  public static final int FOR = 7;
  public static final int MINUS = 30;
  public static final int NOT = 23;
  public static final int SEMICOLON = 17;
  public static final int AND = 13;
  public static final int OR = 10;
  public static final int COMMA = 18;
  public static final int DOTDOT = 21;
  public static final int DIV = 11;
  public static final int LESSOREQUAL = 26;
  public static final int MOREOREQUAL = 28;
  public static final int PLUS = 29;
  public static final int MULTIPLY = 31;
  public static final int ASSIGN = 22;
  public static final int MAIN = 14;
  public static final int IF = 8;
  public static final int RIGTHPAR = 16;
  public static final int OF = 37;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MOD = 12;
  public static final int IDENT = 40;
  public static final int RIGHTBRACE = 34;
  public static final int COLON = 20;
  public static final int ELSE = 9;
  public static final int WHILE = 6;
  public static final int LEFTPAR = 15;
  public static final int LEFTBRACE = 33;
  public static final int DOUBLE_LITERAL = 41;
  public static final int VAR = 2;
  public static final int PROCEDURE = 3;
  public static final int MORE = 27;
  public static final int INTEGER_LITERAL = 38;
}

